// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DECRYPTION_STATE`, `DecryptionKeys`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `custom_open_fn_wrapper`

void setDecryptionKeys({required List<int> key, required List<int> iv}) =>
    RustLib.instance.api.crateApiSimpleSetDecryptionKeys(key: key, iv: iv);

bool bindSecureProtocol({required PlatformInt64 handleAddress}) => RustLib
    .instance
    .api
    .crateApiSimpleBindSecureProtocol(handleAddress: handleAddress);
