// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `stream_handler`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PlayerState`

Future<String> startProxyServer({
  required int port,
  required String filePath,
  required List<int> aesKey,
  required List<int> aesIv,
}) => RustLib.instance.api.crateApiSimpleStartProxyServer(
  port: port,
  filePath: filePath,
  aesKey: aesKey,
  aesIv: aesIv,
);
